config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  devise_for :users

  post "webhook", to: "webhooks#create", as: :webhook

  namespace :admin do
    get "dashboard/index"
    resource :droplet, only: %i[ create update ]
    resources :settings, only: %i[ index edit update ]
    resources :users
    resources :callbacks, only: %i[ index show edit update ] do
      post :sync, on: :collection
    end
  end

  resources :integration_settings, only: %i[create] do
    collection do
      post :test_connection
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/shared/_header.html.erb
<header class="flex h-8 shrink-0 items-center px-8 transition-[width,height] ease-linear w-full">
  <div class="flex-1">
    <% if flash.any? %>
      <div class="flex flex-col gap-2 p-4">
        <% flash.each do |type, message| %>
          <span class="<%= type == 'notice' ? 'text-green-600' : 'text-red-600' %>">
            <%= message %>
          </span>
        <% end %>
      </div>
    <% end %>
  </div>
  <span class="text-sm text-gray-600 mr-4"><%= current_user.email %></span>
  <%= button_to "Sign out",
                destroy_user_session_path,
                method: :delete,
                class: "text-sm text-blue-600 hover:text-orange-600"
  %>
</header>

app/views/shared/_sidebar.html.erb
<div class="flex min-h-0 w-48 flex-col gap-2 overflow-auto">
  <div class="relative flex w-full min-w-0 flex-col p-4">
    <div class="flex h-8 text-xs font-medium"></div>

    <ul class="flex w-full min-w-0 flex-col gap-1">
      <!-- Home Menu Item -->
      <li class="relative">
        <%= link_to admin_dashboard_index_path, class: "flex items-center text-sm font-medium text-gray-900 rounded-md hover:bg-gray-100 px-3 py-2" do %>
          <i class="fa-solid fa-house text-slate-300 mr-2"></i>
          <span>Home</span>
        <% end %>
      </li>

      <!-- Settings Menu Item -->
      <li class="relative">
        <%= link_to admin_settings_path, class: "flex items-center text-sm font-medium text-gray-900 rounded-md hover:bg-gray-100 px-3 py-2" do %>
          <i class="fa-solid fa-gear text-slate-300 mr-2"></i>
          <span>Settings</span>
        <% end %>
      </li>

      <!-- Users Menu Item -->
      <li class="relative">
        <%= link_to admin_users_path, class: "flex items-center text-sm font-medium text-gray-900 rounded-md hover:bg-gray-100 px-3 py-2" do %>
          <i class="fa-solid fa-users text-slate-300 mr-2"></i>
          <span>Users</span>
        <% end %>
      </li>

      <!-- Callbacks Menu Item -->
      <li class="relative">
        <%= link_to admin_callbacks_path, class: "flex items-center text-sm font-medium text-gray-900 rounded-md hover:bg-gray-100 px-3 py-2" do %>
          <i class="fa-solid fa-phone text-slate-300 mr-2"></i>
          <span>Callbacks</span>
        <% end %>
      </li>
    </ul>
  </div>
</div>