config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  devise_for :users

  post "webhook", to: "webhooks#create", as: :webhook

  namespace :admin do
    get "dashboard/index"
    resource :droplet, only: %i[ create update ]
    resources :settings, only: %i[ index edit update ]
    resources :users
    resources :callbacks, only: %i[ index show edit update ] do
      post :sync, on: :collection
    end
  end

  resources :integration_settings, only: %i[create] do
    collection do
      post :test_connection
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/setting.rb
# frozen_string_literal: true

class Setting < ApplicationRecord
  # OpenAPI 3.1.0 dialect for JSON Schema
  META_SCHEMA = "https://spec.openapis.org/oas/3.1/dialect/base"

  validates :name, presence: true, uniqueness: true
  validate :validate_schema
  validate :validate_values

  def self.method_missing(name, *args, **kwargs, &)
    Tasks::Settings.create_defaults if Setting.count.zero?

    if Setting.exists?(name: name.to_s)
      define_singleton_method(name) { Setting.find_by(name: name.to_s) }

      return send(name)
    end

    super
  end

  def self.respond_to_missing?(name, include_private = false)
    Setting.exists?(name: name.to_s) || super
  end

  def method_missing(name, *args, **kwargs, &)
    value = values[name.to_s]
    return value if value.present?

    super
  end

  def respond_to_missing?(name, include_private = false)
    values.key?(name.to_s) || super
  end

private

  def validate_schema
    return errors.add(:schema, "is missing") if schema.nil?
    return nil if JSONSchemer.valid_schema?(schema, meta_schema: META_SCHEMA)

    JSONSchemer.validate_schema(schema, meta_schema: META_SCHEMA).each do |e|
      errors.add(:schema, e["error"])
    end
  rescue StandardError => e
    Rails.logger.error("Error validating schema: #{e.message}")
    errors.add(:schema, "is invalid")
  end

  def validate_values
    return nil if JSONSchemer.schema(schema, meta_schema: META_SCHEMA).valid?(values)

    JSONSchemer.schema(schema, meta_schema: META_SCHEMA).validate(values).each do |e|
      errors.add(:values, e["error"])
    end
  rescue StandardError => e
    # https://github.com/davishmcclurg/json_schemer/issues/215
    # TODO: Rescue JSONSchemer::SchemaError when it's fixed
    Rails.logger.error("Error validating values: #{e.message}")
    errors.add(:values, "is invalid")
  end
end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < AdminController
  def index
    @settings = Setting.order(:name)
  end

  def edit
    @setting = Setting.find(params[:id])
    @name = @setting.name.humanize.titleize
  end

  def update
    @setting = Setting.find(params[:id])
    @setting.update(setting_params)

    render json: { success: true }
  end

private

  def setting_params
    params.require(:setting).permit(values: {})
  end
end

app/views/admin/settings/edit.html.erb
<% content_for :head do %>
  <%= vite_typescript_tag 'settings.tsx' %>
<% end %>
<div class="flex items-center justify-between">
  <div class="flex flex-col gap-1">
    <h1 class="font-custom text-3xl font-bold text-gray-600"><%= @name %></h1>
    <h3 class="text-gray-400"><%= @setting.description %></h3>
  </div>
</div>

<div
  id="root-element"
  data-id="<%= @setting.id %>"
  data-schema="<%= @setting.schema.to_json %>"
  data-initial-data="<%= @setting.values.to_json %>"
  data-index-url="<%= admin_settings_path %>"
></div>

app/views/admin/settings/index.html.erb
<div class="flex items-center justify-between">
  <div class="flex items-center gap-2">
    <h1 class="font-custom text-4xl font-bold text-gray-600">Settings</h1>
  </div>
</div>

<div class="bg-white rounded-lg p-6 border border-gray-100">
  <table class="w-full">
    <thead class="bg-slate-50 border-b border-gray-400">
      <tr>
        <th class="pl-2 text-left text-slate-600">Name</th>
        <th class="pl-2 text-left text-slate-600">Values</th>
      </tr>
    </thead>
    <tbody>
      <% @settings.each do |setting| %>
        <tr class="odd:bg-white even:bg-slate-50 hover:bg-slate-100">
          <td class="pl-2 text-left text-gray-600"><%= link_to setting.name.humanize.titleize, edit_admin_setting_path(setting) %></td>
          <td class="pl-2 text-left text-gray-400 font-mono whitespace-pre"><%= format_settings_values(setting.values) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>